<?xml version="1.0" encoding="unicode"?>
<!DOCTYPE DEPARTMENT[
<!ELEMENT DEPARTMENT (TEACHER+)>
<!ELEMENT TEACHER (SURNAME, NAME, FATHERNAME, AGE, DEGREE, WORKEXP, SALARY)>
<!ELEMENT SURNAME (#PCDATA)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT FATHERNAME (#PCDATA)>
<!ELEMENT AGE (#PCDATA)>
<!ELEMENT DEGREE (#PCDATA)>
<!ELEMENT WORKEXP (#PCDATA)>
<!ELEMENT SALARY (#PCDATA)>
]>
<DEPARTMENT>
<TEACHER>
<SURNAME>Климова</SURNAME>
<NAME>Мария</NAME>
<FATHERNAME>Степановна</FATHERNAME>
<AGE>24</AGE>
<DEGREE>Аспирант</DEGREE>
<WORKEXP>1</WORKEXP>
<SALARY>15000</SALARY>
</TEACHER>
<TEACHER>
<SURNAME>Лопатина</SURNAME>
<NAME>Анна</NAME>
<FATHERNAME>Петровна</FATHERNAME>
<AGE>68</AGE>
<DEGREE>Профессор</DEGREE>
<WORKEXP>45</WORKEXP>
<SALARY>38000</SALARY>
</TEACHER>
<TEACHER>
<SURNAME>Аксёнова</SURNAME>
<NAME>Инна</NAME>
<FATHERNAME>Алексеевна</FATHERNAME>
<AGE>26</AGE>
<DEGREE>Аспирант</DEGREE>
<WORKEXP>3</WORKEXP>
<SALARY>18000</SALARY>
</TEACHER>
<TEACHER>
<SURNAME>Миршников</SURNAME>
<NAME>Дмитрий</NAME>
<FATHERNAME>Вадимович</FATHERNAME>
<AGE>66</AGE>
<DEGREE>Профессор</DEGREE>
<WORKEXP>44</WORKEXP>
<SALARY>40000</SALARY>
</TEACHER>
<TEACHER>
<SURNAME>Дюжин</SURNAME>
<NAME>Илья</NAME>
<FATHERNAME>Владимирович</FATHERNAME>
<AGE>63</AGE>
<DEGREE>Профессор</DEGREE>
<WORKEXP>40</WORKEXP>
<SALARY>30000</SALARY>
</TEACHER>
<TEACHER>
<SURNAME>Лебедушкин</SURNAME>
<NAME>Амброзий</NAME>
<FATHERNAME>Абдулович</FATHERNAME>
<AGE>40</AGE>
<DEGREE>Доцент</DEGREE>
<WORKEXP>20</WORKEXP>
<SALARY>25000</SALARY>
</TEACHER>
<TEACHER>
<SURNAME>Прушкин</SURNAME>
<NAME>Леонтин</NAME>
<FATHERNAME>Митрофанович</FATHERNAME>
<AGE>25</AGE>
<DEGREE>Асипирант</DEGREE>
<WORKEXP>5</WORKEXP>
<SALARY>15000</SALARY>
</TEACHER>
<TEACHER>
<SURNAME>Винчик</SURNAME>
<NAME>Зухра</NAME>
<FATHERNAME>Бельбековна</FATHERNAME>
<AGE>23</AGE>
<DEGREE>Аспирант</DEGREE>
<WORKEXP>2</WORKEXP>
<SALARY>15000</SALARY>
</TEACHER>
<TEACHER>
<SURNAME>Литвини</SURNAME>
<NAME>Марк</NAME>
<FATHERNAME>Алексеевич</FATHERNAME>
<AGE>63</AGE>
<DEGREE>Доктор наук</DEGREE>
<WORKEXP>40</WORKEXP>
<SALARY>40000</SALARY>
</TEACHER>
</DEPARTMENT>
