<?xml version="1.0" encoding="unicode"?>
<!DOCTYPE USERSLIST[
<!ELEMENT USERSLIST (USER+)>
<!ELEMENT USER (ID, NAME, DATEOFBIRTH, AGE)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT DATEOFBIRTH (#PCDATA)>
<!ELEMENT AGE (#PCDATA)>
]>
<USERSLIST>
<USER>
<ID>00000000-0000-0000-0000-000000000000</ID>
<NAME>Anna</NAME>
<DATEOFBIRTH>26.03.1999</DATEOFBIRTH>
<AGE>20</AGE>
</USER>
<USER>
<ID>00000000-0000-0000-0000-000000000000</ID>
<NAME>Anna</NAME>
<DATEOFBIRTH>26.03.1999</DATEOFBIRTH>
<AGE>20</AGE>
</USER>
</USERSLIST>
