<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE USERSLIST[
  <!ELEMENT USERSLIST (USER*)>
  <!ELEMENT USER (ID, NAME, DATEOFBIRTH, AGE)>
  <!ELEMENT ID (#PCDATA)>
  <!ELEMENT NAME (#PCDATA)>
  <!ELEMENT DATEOFBIRTH (#PCDATA)>
  <!ELEMENT AGE (#PCDATA)>
]>
<USERSLIST>
  <USER>
    <ID>d80cdf09-acae-49bd-804b-6868a643b762</ID>
    <NAME>Anya</NAME>
    <DATEOFBIRTH>25.02.2000</DATEOFBIRTH>
    <AGE>19</AGE>
  </USER>
  <USER>
    <ID>30b6fa67-553c-47be-86c0-c1435a2883d8</ID>
    <NAME>Den</NAME>
    <DATEOFBIRTH>25.08.1995</DATEOFBIRTH>
    <AGE>24</AGE>
  </USER>
  <USER>
    <ID>21785fe1-7f3e-4e7c-8238-b16f6f2bd0f2</ID>
    <NAME>Jo</NAME>
    <DATEOFBIRTH>25.02.1998</DATEOFBIRTH>
    <AGE>21</AGE>
  </USER>
  <USER>
    <ID>18a16130-4671-4f69-baef-b854573069c8</ID>
    <NAME>Jyle</NAME>
    <DATEOFBIRTH>25.01.1996</DATEOFBIRTH>
    <AGE>23</AGE>
  </USER>
</USERSLIST>